create table collectionvoca
(
    id   integer generated by default as identity
        primary key,
    name varchar(100)
);

alter table collectionvoca
    owner to postgres;

create table language
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6),
    delete_flag boolean,
    name        varchar(100),
    note        text,
    updated_at  timestamp(6)
);

alter table language
    owner to postgres;

create table level
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6),
    delete_flag boolean,
    description text,
    name        varchar(100),
    updated_at  timestamp(6)
);

alter table level
    owner to postgres;

create table status_lesson
(
    id          integer generated by default as identity
        primary key,
    name_status varchar(20)
);

alter table status_lesson
    owner to postgres;

create table users
(
    id           integer generated by default as identity
        primary key,
    created_at   timestamp(6),
    credit       integer,
    date_birth   date,
    delete_flag  boolean,
    email        varchar(100)
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    last_login   timestamp(6),
    name         varchar(100),
    password     varchar(255),
    phone_number varchar(20),
    point        integer,
    role         varchar(50),
    school       varchar(100),
    username     varchar(100)
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to postgres;

create table feedback
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6),
    description text,
    user_id     integer
        constraint fkpwwmhguqianghvi1wohmtsm8l
            references users
);

alter table feedback
    owner to postgres;

create table notification
(
    id           integer generated by default as identity
        primary key,
    created_at   timestamp(6),
    is_read      boolean,
    link         varchar(255),
    message      text,
    type         varchar(50),
    user_receive integer
        constraint fk513jpjhwmakvip57jhel0ws8w
            references users,
    user_sender  integer
        constraint fkel0p54nbx4v73igl6ntludxhq
            references users
);

alter table notification
    owner to postgres;

create table payment
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6),
    price      numeric(10, 2),
    status     varchar(50),
    user_id    integer
        constraint fkmi2669nkjesvp7cd257fptl6f
            references users
);

alter table payment
    owner to postgres;

create table topic
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6),
    delete_flag boolean,
    description text,
    name        varchar(100),
    note        text,
    type        varchar(50),
    language_id integer
        constraint fkrvlfym1sa4g8g0c9cdy06lyjr
            references language,
    level_id    integer
        constraint fk7an4m7qxxtyhdbihi1q11kfw6
            references level,
    user_id     integer
        constraint fk3qd4k7we4cdll00i6x84afhi8
            references users
);

alter table topic
    owner to postgres;

create table lesson
(
    id            integer generated by default as identity
        primary key,
    created_at    timestamp(6),
    delete_flag   boolean,
    description   text,
    last_practice timestamp(6),
    name          varchar(100),
    note          text,
    paragraph     text,
    status        varchar(50),
    type          varchar(50),
    updated_at    timestamp(6),
    topic_id      integer
        constraint fkni3nqpuau54ygl4lk0o6vu5xn
            references topic
);

alter table lesson
    owner to postgres;

create table history
(
    id        integer generated by default as identity
        primary key,
    answer    text,
    question  text,
    result    boolean,
    lesson_id integer
        constraint fk6wtcgd2wxppn81a0ncnb6xaky
            references lesson,
    user_id   integer
        constraint fkq4kh99ws9lhtls5i3o73gw30t
            references users
);

alter table history
    owner to postgres;

create table status_leson_user
(
    id        integer generated by default as identity
        primary key,
    lesson_id integer
        constraint fkimjusywo0tek85uyosn940po5
            references lesson,
    status    integer
        constraint fk7hpvkx2ndwmse9aiibchysikd
            references status_lesson,
    user_id   integer
        constraint fkbbsq7cjigitpnx4lb563giuok
            references users
);

alter table status_leson_user
    owner to postgres;

create table suggest_vocabulary
(
    id            integer generated by default as identity
        primary key,
    delete_flag   boolean,
    example       text,
    pronunciation varchar(100),
    term          varchar(100),
    type          varchar(50),
    vietnamese    text,
    lesson_id     integer
        constraint fkp8h71tvijjhxc6pkx2cjqsli3
            references lesson
);

alter table suggest_vocabulary
    owner to postgres;

create table vocabulary
(
    id            integer generated by default as identity
        primary key,
    example       text,
    pronunciation varchar(100),
    term          varchar(100),
    type          varchar(50),
    vi            text,
    collection_id integer
        constraint fk3ksh0xy4q7i3525vlbr93vvgb
            references collectionvoca,
    user_id       integer
        constraint fk50fel7tsib4tpnuqa7irn7f5c
            references users
);

alter table vocabulary
    owner to postgres;

