/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserTopicsIndexRouteImport } from './routes/user/topics/index'
import { Route as UserLevelIndexRouteImport } from './routes/user/level/index'
import { Route as UserLessonsIndexRouteImport } from './routes/user/lessons/index'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminTopicIndexRouteImport } from './routes/admin/topic/index'
import { Route as AdminLevelIndexRouteImport } from './routes/admin/level/index'
import { Route as AdminLanguageIndexRouteImport } from './routes/admin/language/index'
import { Route as UserLessonPracticeLessonIdRouteImport } from './routes/user/lesson-practice/$lessonId'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserTopicsIndexRoute = UserTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLevelIndexRoute = UserLevelIndexRouteImport.update({
  id: '/level/',
  path: '/level/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLessonsIndexRoute = UserLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTopicIndexRoute = AdminTopicIndexRouteImport.update({
  id: '/topic/',
  path: '/topic/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLevelIndexRoute = AdminLevelIndexRouteImport.update({
  id: '/level/',
  path: '/level/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLanguageIndexRoute = AdminLanguageIndexRouteImport.update({
  id: '/language/',
  path: '/language/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserLessonPracticeLessonIdRoute =
  UserLessonPracticeLessonIdRouteImport.update({
    id: '/lesson-practice/$lessonId',
    path: '/lesson-practice/$lessonId',
    getParentRoute: () => UserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/language': typeof AdminLanguageIndexRoute
  '/admin/level': typeof AdminLevelIndexRoute
  '/admin/topic': typeof AdminTopicIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/user/lessons': typeof UserLessonsIndexRoute
  '/user/level': typeof UserLevelIndexRoute
  '/user/topics': typeof UserTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/language': typeof AdminLanguageIndexRoute
  '/admin/level': typeof AdminLevelIndexRoute
  '/admin/topic': typeof AdminTopicIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/user/lessons': typeof UserLessonsIndexRoute
  '/user/level': typeof UserLevelIndexRoute
  '/user/topics': typeof UserTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/language/': typeof AdminLanguageIndexRoute
  '/admin/level/': typeof AdminLevelIndexRoute
  '/admin/topic/': typeof AdminTopicIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/user/lessons/': typeof UserLessonsIndexRoute
  '/user/level/': typeof UserLevelIndexRoute
  '/user/topics/': typeof UserTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/'
    | '/user/lesson-practice/$lessonId'
    | '/admin/language'
    | '/admin/level'
    | '/admin/topic'
    | '/admin/user'
    | '/user/lessons'
    | '/user/level'
    | '/user/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/admin'
    | '/user/lesson-practice/$lessonId'
    | '/admin/language'
    | '/admin/level'
    | '/admin/topic'
    | '/admin/user'
    | '/user/lessons'
    | '/user/level'
    | '/user/topics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/user'
    | '/admin/'
    | '/user/lesson-practice/$lessonId'
    | '/admin/language/'
    | '/admin/level/'
    | '/admin/topic/'
    | '/admin/user/'
    | '/user/lessons/'
    | '/user/level/'
    | '/user/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/topics/': {
      id: '/user/topics/'
      path: '/topics'
      fullPath: '/user/topics'
      preLoaderRoute: typeof UserTopicsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/level/': {
      id: '/user/level/'
      path: '/level'
      fullPath: '/user/level'
      preLoaderRoute: typeof UserLevelIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/lessons/': {
      id: '/user/lessons/'
      path: '/lessons'
      fullPath: '/user/lessons'
      preLoaderRoute: typeof UserLessonsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/topic/': {
      id: '/admin/topic/'
      path: '/topic'
      fullPath: '/admin/topic'
      preLoaderRoute: typeof AdminTopicIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/level/': {
      id: '/admin/level/'
      path: '/level'
      fullPath: '/admin/level'
      preLoaderRoute: typeof AdminLevelIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/language/': {
      id: '/admin/language/'
      path: '/language'
      fullPath: '/admin/language'
      preLoaderRoute: typeof AdminLanguageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/lesson-practice/$lessonId': {
      id: '/user/lesson-practice/$lessonId'
      path: '/lesson-practice/$lessonId'
      fullPath: '/user/lesson-practice/$lessonId'
      preLoaderRoute: typeof UserLessonPracticeLessonIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLanguageIndexRoute: typeof AdminLanguageIndexRoute
  AdminLevelIndexRoute: typeof AdminLevelIndexRoute
  AdminTopicIndexRoute: typeof AdminTopicIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminLanguageIndexRoute: AdminLanguageIndexRoute,
  AdminLevelIndexRoute: AdminLevelIndexRoute,
  AdminTopicIndexRoute: AdminTopicIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserLessonPracticeLessonIdRoute: typeof UserLessonPracticeLessonIdRoute
  UserLessonsIndexRoute: typeof UserLessonsIndexRoute
  UserLevelIndexRoute: typeof UserLevelIndexRoute
  UserTopicsIndexRoute: typeof UserTopicsIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserLessonPracticeLessonIdRoute: UserLessonPracticeLessonIdRoute,
  UserLessonsIndexRoute: UserLessonsIndexRoute,
  UserLevelIndexRoute: UserLevelIndexRoute,
  UserTopicsIndexRoute: UserTopicsIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
